{% set name = "greedyreg" %}
{% set version = "0.0.20250712" %}
{% set ref = "f10152c5374da08ee024c4c60ef8882876bd0808" %}
# The upstream greedy repository does not use tags for versioning.
# This package is built against a specific commit hash ({{ ref }}) that corresponds to v1.0.1.
# This version number ({{ version }}) is a date-based version assigned for the purpose of this conda package to reflect the state of the code at commit {{ ref }} and on what date the package was added on conda-forge.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyushkevich/greedy/archive/{{ ref }}.tar.gz
  sha256: 75386be7ca5495ce8a5115770cfe9ee838736d11008d792153bca57d81308919

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - libitk-devel
    - eigen
    - vtk

outputs:
  - name: {{ name|lower }}
    build:
      run_exports:
        - {{ pin_subpackage('greedyreg', max_pin='x.x.x') }}
    requirements:
      run:
        - libitk            
        - eigen             
        - vtk               
        - fftw
    test:
      commands:
        - test -f $PREFIX/bin/greedy                  
        - test -f $PREFIX/lib/libgreedyapi.so        
        - test -f $PREFIX/include/GreedyAPI.h         
        - greedy -version                             

  - name: {{ name|lower }}-devel
    build:
      run_exports:
        - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}
    requirements:
      host:
        - {{ pin_subpackage(name|lower, exact=True) }}
      run:
        - {{ pin_subpackage(name|lower, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/cmake/Greedy/GreedyConfig.cmake  
        - test -d $PREFIX/include                              

about:
  home: https://sites.google.com/view/greedyreg/
  license: GPL-3.0-or-later
  license_file: COPYING.txt
  summary: 'Very fast greedy diffeomorphic registration code.'
  description: |
    A really fast CPU-based deformable image registration tool that could 
    be used in applications where many images have to be registered in 
    parallel - like multi-atlas image segmentation.
  dev_url: https://github.com/pyushkevich/greedy

extra:
  feedstock-name: {{ name|lower }}
  recipe-maintainers:
    - Dhananjhay
